### ISSUE TITLE
README example invalid

### ISSUE THREAD

**Issue by travisghansen** [kubernetes-csi/node-driver-registrar#56]
There a couple problems here:

```
      containers:
        - name: csi-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
          args:
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/<drivername.example.com>/csi.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/<plugin> /registration/<drivername.example.com>-reg.sock"]
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/<drivername.example.com>/
            type: DirectoryOrCreate
```

The `preStop` command doesn't work with the latest images as apparently `sh` is no longer in the image.

Also the plugin removal from what i can tell should be `/csi` instead of `/registration`.

**Comment by Madhu-1** [comment]
https://github.com/kubernetes-csi/node-driver-registrar/pull/61 should fix this issue

**Comment by Colstuwjx** [comment]
Hi @Madhu-1 , I've seen your PR #61 , it only removed reg.sock, and `/csi/csi.sock` still exists, should we also clean this socket file?

relative issue I met: https://github.com/TencentCloud/kubernetes-csi-tencentcloud/issues/32.
